### ISSUE TITLE
ngVenezuela, Comunidad de Desarrolladores y Entusiastas de AngularJs en Venezuela

### ISSUE THREAD

**Issue by Villanuevand** [UptaJS/Practicas-AngularJS#5]
Hola, primero quier disculparme por la aproximación de esta manera,  mi nombre es Andrés Villanueva, soy administrador de [ngVenezuela](www.ngvenezuela.org.ve "Comunidad de Desarrolladores y Entusiastas de AngularJS"), que es una comunidad venezolana encargada de reunir y ayudar a los desarrolladores de AngularJs en nuestro país, ya somos casi 100 integrantes u me gustaría poner a su disposición ngVenezuela, para cualquier problema, duda, inquietud que tengan sobre este maravilloso framework. 

Tenemos como plataforma de preguntas y respuestas un [Grupo en Google](https://groups.google.com/forum/?hl=es#!forum/ngvenezuela) donde puede agregarse y postear sus preguntas y ayudar a otros con respuestas. En ese mail list estamos ofreciendo un curso gratuito de AngularJs de la gente de Video2Brain llamado ["Angular de 0 a 100"](https://www.video2brain.com/mx/cursos/angularjs-de-0-a-100) solo solicitandolo por el [siguiente hilo](https://groups.google.com/forum/?hl=es#!topic/ngvenezuela/_U_YkBhZlv4). En Github pueden conseguirnos como [ngVenezuela](https://github.com/ngvenezuela "ngVenezuela en Github")

Ojalá podamos establecer relaciones para ayudar a expandir los conocimientos sobre Angular y aumentar nuestro nivel. 

Saludos. 

Andrés Villanueva.

**Comment by aranajhonny** [comment]
hola ,saludos soy estudiante de la universidad politécnica territorial del estado aragua (UPTA), precisamente apenas estoy aprendiendo angularJS , junto con otros compañeros de clase,ya tome el curso de video2brain de angularJS hace poco y de ahí partió mi interés por esta maravillosa herramienta, estoy ya en su grupo de telegram aunque no muy activamente, pronto estaré por allí compartiendo algunos manuales, también estoy tratando de traducir algunos que están en ingles y aveces a todos nos se nos hace tan fácil leer en este idioma. gracias por la invitación.

saludos.- Jhonny Arana

**Comment by Villanuevand** [comment]
Hola @aranajhonny 
Que bueno que estés comenzando a desarrollar con Angular, en caso de que tengas alguna inquietud o duda sobre el framework, crea un hilo en nuestro Grupo de Google y con gusto te responderemos.
